modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[dependencies."${mod_id}"]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
side="BOTH"# Here's another dependency
[[mixins]]
config="divineartifacts.mixins.json"

[[dependencies."${mod_id}"]]
modId="curios"
mandatory=true
versionRange="[5.8,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="attributeslib"
mandatory=true
versionRange="[1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="irons_spellbooks"
mandatory=true
versionRange="[1.20.1-3.1,)"
ordering="NONE"
side="BOTH"

